import { Container } from "@/components/shared/container";
import { Header } from "@/components/shared/header";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  };
  
  export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
    return (
        <main className="min-h-screen">
          <Header/>
            {children}
        </main>
    );
  }
  